surenav_ll:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200 

  # Position Controllers ---------------------------------------
  r_hip_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_yaw_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  r_hip_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_roll_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  r_hip_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_pitch_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  r_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_knee_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  r_ankle_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ankle_pitch_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  r_ankle_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_ankle_roll_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  l_hip_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_yaw_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  l_hip_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_roll_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  l_hip_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_pitch_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  l_knee_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_knee_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  l_ankle_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ankle_pitch_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
  l_ankle_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_ankle_roll_joint
    pid: {p: 10000.0, i: 0.01, d: 60.0}
